services:
  - type: web
    name: ayurhealth-dosha-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
